version: 0.2

phases:
  pre_build:
    commands:
      - echo ${DOCKERHUB_TOKEN} | docker login -u ${DOCKERHUB_USER} --password-stdin   # Line 5: Fixed variable name here
  build:
    commands:
      - docker build -t my-angular-app:latest .  # Line 8
  post_build:
    commands:
      - docker tag my-angular-app:latest ${DOCKERHUB_USER}/my-angular-app:latest   # Line 10
      - docker push ${DOCKERHUB_USER}/my-angular-app:latest  # Line 11: Corrected this command
